### PR TITLE
last one for this week but another will come after launch next week

### PR DESCRIPTION
**Pull request by rmpare**

### CODE REVIEW

**Comment by christiancasey** [comment]
Merge conflict. Cut out the conflicting file, pull upstream, put your changes to that file back in, and then do a commit-push-PR.

**Comment by rmpare** [comment]
Hi Christian,
This may be basic, but how do I know where the conflict lies? I have no "history" so to speak of the conflict, so I don't know which entry to pull out.



Rhiannon Pare

Graduate Student

Classical Art and Archaeology

Princeton University

________________________________

**Comment by christiancasey** [comment]
It says when you try to merge. There’s a list of conflicting files with their full paths.

**Comment by rmpare** [comment]
So do I need to try to merge again to keep track of the issues? Or is there a history somewhere that I can pull them from?



Rhiannon Pare

Graduate Student

Classical Art and Archaeology

Princeton University

________________________________

**Pull request closed without merging**
