### PR TITLE
edits and new adds

### PR DESCRIPTION
**Pull request by rmpare**
I think this should be alright and not destroy everything. :)

### CODE REVIEW

**Comment by christiancasey** [comment]
Hi Rhiannon,

This pr has multiple merge conflicts. Try pulling `upstream master` and fixing them and then submit another pr.

As always, contact me if you need help.

Christian

**Comment by rmpare** [comment]
Hi Christian,

I have pulled the master and pushed again but the same red errors are coming up. How do I fix them? Additionally, is there somewhere to determine how to add images in?

Hope you had a good move


Rhiannon


Rhiannon Pare

Graduate Student

Classical Art and Archaeology

Princeton University

________________________________

**Comment by christiancasey** [comment]
Hi Rhiannon,

Move was pretty good. Uneventful really, which is what you want. I think that means that you and I are on the same timezone now. That’ll definitely make things easier if I need to jump in and help with this. I want to encourage you to try to fix it yourself though before I inject myself.

Those red errors are probably merge conflicts. You could move your new changed files into a new empty temporary folder (all the files that show up in the conflicted list), pull the upstream and merge, then replace the files from the pull with your new ones. Then add commit push pull again. That should fix it.

Try that and let me know how it goes.

I don’t know that I understand your question about the images. Remind me of that after we fix this merge issue and I can look at it.

Christian

**Comment by rmpare** [comment]
Hi Casey,

Uneventful is always good. Even more so in these trying times. I think we are on the same time zone now.

I've done what you suggested. The red is still there but it says that it is able to merge? So we shall see?


Rhiannon Pare

Graduate Student

Classical Art and Archaeology

Princeton University

________________________________

**Comment by christiancasey** [comment]
We shall see!

**Comment by rmpare** [comment]
Looks like it all worked out? Awesome. And I was referencing how to insert images into the individual pages. I've been trying to figure it out.
I have index.md
./add_index.sh
./add    - images on github. I have been trying to reverse engineer this. Or engineer it.


Rhiannon Pare

Graduate Student

Classical Art and Archaeology

Princeton University

________________________________

**Comment by rmpare** [comment]
I think I've figured out the images! Hopefully. This will be the test draft. Also, is there a way to "nest" entries? I have several that are under the umbrella of larger ones but rather than put a ton of information on one page, I am trying to break them up but still tie them to the larger whole.

Rhiannon


Rhiannon Pare

Graduate Student

Classical Art and Archaeology

Princeton University

________________________________

**Comment by christiancasey** [comment]
Nesting entries is a good question. It’s come up in the design process a few times. The answer I found before was “I don’t know”. It seems like it should be possible, but it’s not something that Hugo is designed to do, so we would need some sort of workaround. In the past, we’ve decided against it for the time but planned to come back to it later. As of now, I don’t know a way unfortunately.

**Pull request closed without merging**
