### PR TITLE
attempt to correct gibberish in Tyrus keywords section & show Petra missing figures

### PR DESCRIPTION
**Pull request by LXB41**

### CODE REVIEW

**Comment by christiancasey** [comment]
There’s a conflict in the Arabia Tyrus entry. Take that one out, pull upstream, then put it back. After that your PR should work. Let me know if it doesn’t work out and I’ll come help.

**Comment by LXB41** [comment]
I removed the Tyrus folder and then pulled the upstream master. In Atom. a Tyrus folder appeared but did not have an image folder or an index.md file. I dropped a copy of the images folder in but did not know if I should copy the previous index or not. Either way, I get the following message when I try Hugo.  When I entered "hugo help new" the information produced was no help to me.

[cid:39da74f1-3cb8-4c2e-bc61-38caae02aa29]
________________________________

**Comment by christiancasey** [comment]
I don’t know what that error means either, but you need the _index.md. I’m guessing the error also said something about an invalid short code. If you put it back, the error should go away.

**Comment by LXB41** [comment]
I had already tried it without and with the index file but with the same result.  Now, I deleted the Tyrus folder that came from the upstream master and replaced it with the folder I had removed. Same result. When I type "hugo help new" I get this:

[cid:5845ba3a-0b93-47c7-8f40-d58f9deeff97]
________________________________

**Comment by christiancasey** [comment]
Hi Leigh-Ann,

I’m very sorry that it’s giving you so much trouble. I’ll do whatever I can to help. 

For starters, does Hugo have any more output, or is it only that code? I don’t know how to interpret those codes, but if there is any other output, perhaps I can use it to offer a way forward. 

Best,
Christian

**Comment by LXB41** [comment]
I think I am just making it worse by trying to fix it. I tried creating the tyrus file by scratch, but the template was not the same. Then I tried doing another git pull and I got this.

[cid:7878ae57-0e2c-4c10-94de-21e2443f21f8]

I know that you have more than enough to do right now, so maybe this should just wait to be fixed after the other edit work is completed.




________________________________

**Comment by christiancasey** [comment]
Oh I always have plenty of things to work on, but I'm also happy to help you with this problem. I think the only thing to do is to meet via zoom and look at it. Do you have time today to do that?

**Comment by LXB41** [comment]
Sorry, I had office hours and didn't realize you had responded. I could do a Zoom this afternoon, but it is probably already too late for you.
________________________________

**Comment by christiancasey** [comment]
We can. How about 14:00 EDT/20:00 CET?

**Comment by LXB41** [comment]
OK. In one hour.
________________________________

**Comment by christiancasey** [comment]
Yes.

**Pull request closed without merging**
